# Generated by Django 3.1.2 on 2020-11-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='admin',
            new_name='user',
        ),
    ]
