# Generated by Django 3.1.2 on 2020-11-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering_app', '0002_orderdetails_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_ordering_app.vendor'),
        ),
    ]
