# Generated by Django 3.1.2 on 2020-11-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering_app', '0003_auto_20201109_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='admin',
        ),
    ]
