# Generated by Django 3.1.2 on 2020-11-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering_app', '0004_auto_20201113_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_picker',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
