# Generated by Django 3.1.2 on 2020-11-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering_app', '0005_product_color_picker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_picker',
        ),
        migrations.AddField(
            model_name='vendor',
            name='color_picker',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
