# Generated by Django 3.1.2 on 2020-11-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering_app', '0006_auto_20201114_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
