# Generated by Django 3.1.2 on 2020-11-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering_app', '0009_auto_20201119_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
