# Generated by Django 3.1.2 on 2020-11-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering_app', '0010_product_price1'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='offer_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
