# Generated by Django 3.1.2 on 2020-11-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering_app', '0012_auto_20201121_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='refered_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
