# Generated by Django 3.1.2 on 2020-11-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering_app', '0013_customer_refered_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='product_total',
            field=models.FloatField(default=0, null=True),
        ),
    ]
