# Generated by Django 3.1.2 on 2020-12-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering_app', '0015_offer_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='expiry_date',
        ),
    ]
