# Generated by Django 3.1.2 on 2020-12-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering_app', '0016_remove_offer_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
